spring:
  application:
    name: auth-service
  cloud:
    config:
      fail-fast: true
  config:
    import: "optional:configserver:http://config-service:8088"
    
server:
  port: 8011
  servlet:
    context-path: /auth-service
    
logstash:
  service: localhost:5000