spring:
  application:
    name: discovery-service
    
      
  security:
    basic:
      enabled: false
#    user:
#      name: gintaa-app
#      password: passw0rd
      
  config:
    import: "optional:configserver:http://localhost:8088"

server:
  port: 8001
      
eureka:
  instance:
    hostname: localhost
    port: 8001
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8001}/eureka/
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: false
    fetch-registry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#      numberRegistrySyncRetries: 0
#      maxThreadsForPeerReplication: 0

