version: '3.8'
services:
  config-service:
    image: arkit/cognizant-e-auction:config-service-docker-0.0.1
    build: .
    ports:
      - "8088:8088"
    restart: always
#    depends_on:
#      - discovery-service
    networks:
      - e-auction-network
      
  discovery-service:
    image: arkit/cognizant-e-auction:discovery-service-docker-0.0.1
    build: .
    ports:
      - "8001:8001"
    restart: always
    depends_on: 
      - config-service
    networks:
      - e-auction-network
      
  gateway-service:
    image: arkit/cognizant-e-auction:gateway-service-docker-0.0.1
    build: .
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - config-service
      - discovery-service
    networks:
      - e-auction-network
      
  seller-service:
    image: arkit/cognizant-e-auction:seller-service-docker-0.0.1
    build: .
    ports:
      - "8005:8005"
      - "5005:5005"
    restart: always
    depends_on:
      - config-service
      - discovery-service
      - postgresdb 
    networks:
      - e-auction-network
      
      
  product-service:
    image: arkit/cognizant-e-auction:product-service-docker-0.0.1
    build: .
    ports:
      - "8002:8002"
      - "5006:5006"
    restart: always
    depends_on:
      - config-service
      - discovery-service
      - postgresdb 
    networks:
      - e-auction-network
      
  buyer-service:
    image: arkit/cognizant-e-auction:buyer-service-docker-0.0.1
    build: .
    ports:
      - "8004:8004"
      - "5007:5007"
    restart: always
    depends_on:
      - config-service
      - discovery-service
      - postgresdb
    networks:
      - e-auction-network
      
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgresdb:/var/lib/postgresql/data
    networks:
      - e-auction-network
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db

  axonserver:
    image: axoniq/axonserver:latest-dev
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - e-auction-network
      
volumes:
  postgresdb:
    driver: local
  mongodb_data_container:
      
networks:
  e-auction-network: