spring:
  application:
    name: auth-service
  datasource:    
    datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:postgresdb}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:authdb}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
    
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher
  config:
    import: "optional:configserver:http://config-service:8088"
    
  h2:
    console:
      enabled: true
      path: /h2-ui

server:
  port: 8011
  servlet:
    context-path: /auth-service
    
auth:
  remote:
    services:
      user:
        url:
        name: user-service 
        
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  token:
    validity: 86400000  #24h       

logstash:
  service: localhost:5000
          
eureka:
  client:
    serviceUrl:
      #defaultZone: http://gintaa-app:passw0rd@${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8001}/eureka/
      defaultZone: http://${EUREKA_HOST:discovery-service}:${EUREKA_PORT:8001}/eureka/
    register-with-eureka: ${ENABLE_SERVICE_REGISTRATION:true}
    fetchRegistry: true
  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
    preferIpAddress: true
#    instanceId: ${HOST_IP:127.0.0.1}
#    ip-address: ${HOST_IP:127.0.0.1}
#    hostname: ${HOST_NAME:auth-service} 
    
