spring:
  application:
    name: seller-service
  datasource:
    url: jdbc:h2:mem:sellerdb;MODE=MySQL
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties.hibernate.format_sql: true
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-ui
  config:
    import: "optional:configserver:http://localhost:8088"
      

server:
  port: 8005
  servlet:
    context-path: /seller-service
        
seller:
  remote:
    services:
      product:
        url: http://localhost:8090
        name: product-service
      buyer:
        url: http://localhost:8090
        name: buyer-service            
        
eureka:
  client:
    serviceUrl:
      #defaultZone: http://gintaa-app:passw0rd@${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8001}/eureka/
      defaultZone: http://${EUREKA_HOST:discovery-service}:${EUREKA_PORT:8001}/eureka/
    register-with-eureka: ${ENABLE_SERVICE_REGISTRATION:true}
    fetchRegistry: true
  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
    preferIpAddress: true
#    instanceId: ${HOST_IP:127.0.0.1}
#    ip-address: ${HOST_IP:127.0.0.1}
#    hostname: ${HOST_NAME:seller-service}   
    
