spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    config:
      fail-fast: true
  config:
    import: "optional:configserver:http://config-service:8088"
    
server:
  port: 8090
  servlet:
    context-path: /gateway-service
    
logstash:
  service: localhost:5000