spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: productModule
        uri: lb://product-service
        predicates:
        - Path=/product-service/**
      - id: buyerModule
        uri: lb://buyer-service
        predicates:
        - Path=/buyer-service/**
      - id: sellerModule
        uri: lb://seller-service
        predicates:
        - Path=/seller-service/**
  config:
    import: "optional:configserver:http://localhost:8088"

server:
  port: 8090
  servlet:
    context-path: /gateway-service
        
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
                
eureka:
  client:
    serviceUrl:
      #defaultZone: http://gintaa-app:passw0rd@${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8001}/eureka/
      defaultZone: http://${EUREKA_HOST:discovery-service}:${EUREKA_PORT:8001}/eureka/
    register-with-eureka: ${ENABLE_SERVICE_REGISTRATION:true}
    fetchRegistry: true
  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
     preferIpAddress: true
#    instanceId: ${HOST_IP:127.0.0.1}
#    ip-address: ${HOST_IP:127.0.0.1}
#    hostname: ${HOST_NAME:gateway-service}   
    
