spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: true
  config:
    import: "optional:configserver:http://config-service:8088"
server:
  port: 8009
  servlet:
    context-path: /user-service
  
        
logstash:
  service: localhost:5000
