spring:
  application:
    name: product-service
  cloud:
    config:
      fail-fast: true
  config:
    import: "optional:configserver:http://config-service:8088"
      

server:
  port: 8002
  servlet:
    context-path: /product-service

logstash:
  service: localhost:5000
