server:
  port: 8088
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pavankumar-mca51/e-auction-config
          search-paths: '{application}'
          clone-on-start: true
          
          
config-logstash:
  service: localhost:5000