server:
  port: 8088
spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/configs
        git:
          uri: https://github.com/arkitdas/e-auction-app/tree/feature/cqrs-kafka/configs
#          search-paths: '{application}'
#          clone-on-start: true
          
          
config-logstash:
  service: localhost:5000