server:
  port: 8088
spring:
  application:
    name: config-service
  cloud:
    config:
#      request-read-timeout:
#      request-connect-timeout: 
      server:
        git:
          uri: https://github.com/arkitdas/config-repo.git
          default-label: main
          
          
config-logstash:
  service: localhost:5000