server:
  port: 8088
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arkitdas/config-repo
          
          
config-logstash:
  service: localhost:5000